name: 'OpenJDK Build All Platforms'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  prepare:
    name: 'Prepare the run'
    runs-on: self-hosted
    outputs:
      linux: 'true'
      macos: 'true'
      windows: 'true'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

  # --- СБОРКА LINUX ---
  build-linux:
    name: linux-x64
    needs: prepare
    uses: ./.github/workflows/build-linux.yml
    with:
      platform: linux-x64
      gcc-major-version: '10'
    if: needs.prepare.outputs.linux == 'true'

  # --- СБОРКА MACOS ---
  build-macos:
    name: macos-aarch64
    needs: prepare
    uses: ./.github/workflows/build-macos.yml
    with:
      platform: macos-aarch64
      runs-on: 'macos-15'
      xcode-toolset-version: '16.4'
    if: needs.prepare.outputs.macos == 'true'

  # --- СБОРКА WINDOWS ---
  build-windows:
    name: windows-x64
    needs: prepare
    uses: ./.github/workflows/build-windows.yml
    with:
      platform: windows-x64
      msvc-toolset-version: '14.44'
      msvc-toolset-architecture: 'x86.x64'
    if: needs.prepare.outputs.windows == 'true'

  # --- ТЕСТЫ (Опционально) ---
  test-linux:
    needs: build-linux
    uses: ./.github/workflows/test.yml
    with:
      platform: linux-x64
      runs-on: ubuntu-22.04

  test-windows:
    needs: build-windows
    uses: ./.github/workflows/test.yml
    with:
      platform: windows-x64
      runs-on: windows-2025
