name: 'OpenJDK Build'

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:

jobs:
  prepare:
    name: 'Prepare the run'
    runs-on: self-hosted
    outputs:
      # Оставляем только то, что тебе нужно
      linux-x64: 'true'
      macos-aarch64: 'true'
      windows-x64: 'true'
      # Остальное выключаем, но оставляем переменные, чтобы не было ошибок
      linux-x86-hs: 'false'
      linux-x64-variants: 'false'
      linux-cross-compile: 'false'
      macos-x64: 'false'
      windows-aarch64: 'false'
      docs: 'false'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        # Убрали sparse-checkout, который вешал гит

  # --- СБОРКА LINUX ---
  build-linux-x64:
    name: linux-x64
    needs: prepare
    if: needs.prepare.outputs.linux-x64 == 'true'
    uses: ./.github/workflows/build-linux.yml
    with:
      platform: linux-x64
      gcc-major-version: '10'

  # --- СБОРКА MACOS ---
  build-macos-aarch64:
    name: macos-aarch64
    needs: prepare
    if: needs.prepare.outputs.macos-aarch64 == 'true'
    uses: ./.github/workflows/build-macos.yml
    with:
      platform: macos-aarch64
      runs-on: 'macos-15'
      xcode-toolset-version: '16.4'

  # --- СБОРКА WINDOWS ---
  build-windows-x64:
    name: windows-x64
    needs: prepare
    if: needs.prepare.outputs.windows-x64 == 'true'
    uses: ./.github/workflows/build-windows.yml
    with:
      platform: windows-x64
      msvc-toolset-version: '14.44'
      msvc-toolset-architecture: 'x86.x64'
